# 所有环境公用的配置属性
management:
  endpoint:
    health:
      show-details : always
  endpoints:
    web:
      exposure:
        include : '*'
info:
  app-name : spring-boot-demo
  author : JavaEdge
  email : sss2855845850@gmail.com

# 连字符
spring:
  profiles:
    active: dev
---
# profile=x的专用属性,即某个环境下的专用属性
# 开发环境
spring:
  profiles: dev

---
# 生产环境
spring:
  profiles: prod

server:
  tomcat:
    max-threads: 300
    max-connections: 1000